const express=require('express');const fs=require('fs');const path=require('path');
const app=express();const PORT=process.env.PORT||3000;const DB=path.join(__dirname,'data.json');
app.use(express.json({limit:'100kb'}));app.use(express.static(__dirname));
function emptyDB(){return {users:[],produce:[],buyers:[],orders:[],transactions:[],routes:[],qualityChecks:[],disputes:[],notifications:[]}}
function readDB(){if(!fs.existsSync(DB))return emptyDB();const db=JSON.parse(fs.readFileSync(DB,'utf8'));for(const k of Object.keys(emptyDB()))if(!Array.isArray(db[k]))db[k]=[];return db}
function writeDB(db){fs.writeFileSync(DB,JSON.stringify(db,null,2))}function id(p){return p+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}function val(v){return typeof v==='string'?v.trim():v}function order(db,idv){return db.orders.find(o=>o.id===idv)}
app.get('/api/state',(q,s)=>s.json(readDB()));
app.post('/api/register',(req,res)=>{const db=readDB();const name=val(req.body.name),phone=val(req.body.phone),role=val(req.body.role),language=val(req.body.language)||'en';if(!name||!phone||!role)return res.status(400).json({error:'Name, phone and role are required.'});if(!['farmer','buyer','logistics','quality','admin'].includes(role))return res.status(400).json({error:'Invalid role.'});if(role==='admin')return res.status(403).json({error:'Admin is not created through public registration.'});if(String(phone).replace(/\D/g,'').length<10)return res.status(400).json({error:'Enter a valid phone number.'});const u={id:id('USR'),name,phone,role,language,createdAt:new Date().toISOString()};db.users.push(u);writeDB(db);res.json(u)});
app.post('/api/produce',(req,res)=>{const db=readDB(),b=req.body;const quantity=Number(b.quantity),price=Number(b.price);if(!b.farmer||!b.crop||!quantity||quantity<=0||!b.date||!b.location||!price||price<=0)return res.status(400).json({error:'Farmer, crop, quantity, date, location and expected price are required.'});const item={id:id('PRD'),status:'AVAILABLE',qualityStatus:'PENDING_INSPECTION',createdAt:new Date().toISOString(),farmer:val(b.farmer),crop:val(b.crop),quantity,remainingQuantity:quantity,price,unit:b.unit||'kg',date:b.date,location:val(b.location),urgency:'NORMAL'};db.produce.push(item);db.notifications.push({id:id('NTF'),to:item.farmer,message:`Your ${item.crop} listing is submitted at ₹${price}/kg.`,createdAt:new Date().toISOString()});writeDB(db);res.json(item)});
app.post('/api/produce/price',(req,res)=>{const db=readDB(),p=db.produce.find(x=>x.id===req.body.produceId);if(!p)return res.status(404).json({error:'Produce not found.'});const price=Number(req.body.price);if(!price||price<=0)return res.status(400).json({error:'Enter a valid price.'});p.price=price;p.priceUpdatedAt=new Date().toISOString();p.urgency='PRICE_UPDATED';writeDB(db);res.json(p)});
app.post('/api/buyer-request',(req,res)=>{const db=readDB(),b=req.body,q=Number(b.quantity);if(!b.buyer||!b.crop||!q||q<=0)return res.status(400).json({error:'Buyer, crop and quantity are required.'});const r={id:id('REQ'),status:'OPEN',buyer:val(b.buyer),crop:val(b.crop),quantity:q,date:b.date||'',location:val(b.location)||'',maxPrice:b.maxPrice?Number(b.maxPrice):null,createdAt:new Date().toISOString()};db.buyers.push(r);writeDB(db);res.json(r)});
app.post('/api/order',(req,res)=>{const db=readDB(),b=req.body,q=Number(b.quantity),p=db.produce.find(x=>x.id===b.produceId&&x.status==='AVAILABLE');if(!p)return res.status(404).json({error:'Selected crop listing is not available.'});if(!b.buyer||!q||q<=0||q>Number(p.remainingQuantity))return res.status(400).json({error:'Choose a valid quantity within the available amount.'});const price=Number(b.price||p.price);if(price<=0)return res.status(400).json({error:'Invalid price.'});const o={id:id('ORD'),buyer:val(b.buyer),farmer:p.farmer,produceId:p.id,crop:p.crop,quantity:q,price,status:'BUYER_PENDING_CONFIRMATION',qualityStatus:'PENDING_INSPECTION',paymentStatus:'PENDING_QUALITY',logisticsStatus:'PENDING_ACCEPTANCE',createdAt:new Date().toISOString()};db.orders.push(o);writeDB(db);res.json(o)});
app.post('/api/order/confirm',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});if(o.status!=='BUYER_PENDING_CONFIRMATION')return res.status(400).json({error:'Order is not awaiting customer confirmation.'});const p=db.produce.find(x=>x.id===o.produceId);if(!p||p.remainingQuantity<o.quantity)return res.status(400).json({error:'Requested quantity is no longer available.'});p.remainingQuantity-=o.quantity;if(p.remainingQuantity===0)p.status='RESERVED';o.status='BUYER_CONFIRMED';o.buyerConfirmedAt=new Date().toISOString();db.notifications.push({id:id('NTF'),to:o.farmer,message:`Customer confirmed ${o.quantity} kg ${o.crop}. Logistics can accept pickup.`,createdAt:new Date().toISOString()});writeDB(db);res.json(o)});
app.post('/api/order/accept-pickup',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});if(o.status!=='BUYER_CONFIRMED')return res.status(400).json({error:'Customer must confirm before logistics acceptance.'});o.logisticsStatus='ACCEPTED';o.status='PICKUP_ACCEPTED';o.logisticsAcceptedBy=val(req.body.driver)||'Logistics';o.logisticsAcceptedAt=new Date().toISOString();db.notifications.push({id:id('NTF'),to:o.farmer,message:`Logistics accepted pickup for order ${o.id}.`,createdAt:new Date().toISOString()});writeDB(db);res.json(o)});
app.post('/api/order/picked-up',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});if(o.status!=='PICKUP_ACCEPTED')return res.status(400).json({error:'Pickup must be accepted first.'});o.status='PICKED_UP';o.pickedUpAt=new Date().toISOString();writeDB(db);res.json(o)});
app.post('/api/payment',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});const tx={id:id('TXN'),orderId:o.id,amount:Number(req.body.amount||o.quantity*o.price),status:'PENDING_QUALITY',createdAt:new Date().toISOString()};db.transactions.push(tx);o.paymentStatus='PENDING_QUALITY';writeDB(db);res.json(tx)});
app.post('/api/route',(req,res)=>{const db=readDB();const r={id:id('RTE'),status:'ACTIVE',createdAt:new Date().toISOString(),...req.body};db.routes.push(r);writeDB(db);res.json(r)});
app.post('/api/quality-check',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});if(!['PICKED_UP','PICKUP_ACCEPTED'].includes(o.status))return res.status(400).json({error:'Quality check starts after logistics accepts or records pickup.'});const decision=String(req.body.decision||'').toUpperCase();if(!['ACCEPTED','ADJUSTMENT','REJECTED'].includes(decision))return res.status(400).json({error:'Invalid quality decision.'});const damage=Math.max(0,Math.min(100,Number(req.body.damagePct||0)));const qc={id:id('QC'),orderId:o.id,grade:val(req.body.grade)||'B',damagePct:damage,decision,notes:val(req.body.notes)||'',inspector:val(req.body.inspector)||'Quality Agent',createdAt:new Date().toISOString()};db.qualityChecks.push(qc);o.qualityStatus=decision;o.qualityCheckId=qc.id;o.qualityCheckedAt=qc.createdAt;if(decision==='ACCEPTED'){o.status='QUALITY_ACCEPTED';o.paymentStatus='RELEASED_DEMO'}else if(decision==='ADJUSTMENT'){o.status='QUALITY_ADJUSTMENT';o.paymentStatus='ON_HOLD'}else{o.status='QUALITY_REJECTED';o.paymentStatus='ON_HOLD'}db.notifications.push({id:id('NTF'),to:o.buyer,message:`Quality result for ${o.crop}: ${decision}, Grade ${qc.grade}.`,createdAt:new Date().toISOString()},{id:id('NTF'),to:o.farmer,message:`Quality result for ${o.crop}: ${decision}, Grade ${qc.grade}.`,createdAt:new Date().toISOString()});writeDB(db);res.json({order:o,qualityCheck:qc})});
app.post('/api/dispute',(req,res)=>{const db=readDB(),o=order(db,req.body.orderId);if(!o)return res.status(404).json({error:'Order not found.'});const reason=val(req.body.reason);if(!reason)return res.status(400).json({error:'Dispute reason is required.'});const d={id:id('DSP'),orderId:o.id,raisedBy:val(req.body.raisedBy)||'User',reason,status:'OPEN',createdAt:new Date().toISOString()};db.disputes.push(d);o.status='DISPUTE_OPEN';o.paymentStatus='ON_HOLD';writeDB(db);res.json(d)});
app.post('/api/dispute/resolve',(req,res)=>{const db=readDB(),d=db.disputes.find(x=>x.id===req.body.disputeId);if(!d)return res.status(404).json({error:'Dispute not found.'});const dec=String(req.body.decision||'').toUpperCase();if(!['FAVOUR_FARMER','FAVOUR_BUYER','PARTIAL_SETTLEMENT'].includes(dec))return res.status(400).json({error:'Invalid decision.'});d.status='RESOLVED';d.decision=dec;d.resolutionNote=val(req.body.note)||'';d.resolvedAt=new Date().toISOString();const o=order(db,d.orderId);if(o){o.status='DISPUTE_RESOLVED';o.paymentStatus=dec==='FAVOUR_FARMER'?'RELEASED_DEMO':dec==='FAVOUR_BUYER'?'REFUND_REVIEW':'PARTIAL_SETTLEMENT_DEMO'}writeDB(db);res.json({dispute:d,order:o})});
app.post('/api/urgent-sale',(req,res)=>{const db=readDB(),p=db.produce.find(x=>x.id===req.body.produceId);if(!p)return res.status(404).json({error:'Produce not found.'});p.urgency='URGENT';p.urgentAt=new Date().toISOString();db.notifications.push({id:id('NTF'),to:'BUYERS',message:`Urgent ${p.crop} available: ${p.remainingQuantity||p.quantity} kg at ₹${p.price}/kg near ${p.location}.`,createdAt:new Date().toISOString()});writeDB(db);res.json(p)});
app.post('/api/notification',(req,res)=>{const db=readDB();const n={id:id('NTF'),to:val(req.body.to)||'User',channel:val(req.body.channel)||'SMS_DEMO',message:val(req.body.message)||'',createdAt:new Date().toISOString()};db.notifications.push(n);writeDB(db);res.json(n)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,()=>console.log(`AgriTrust running at http://localhost:${PORT}`));
